### ISSUE TITLE
RTEMS partitions

### ISSUE THREAD

**Issue by leonpollak** [DLR-RY/outpost-core#2]
Hello, again.
RTEMS has the great instrument - memory partitions.
I didn't find its implementation in the OUTPOST - did I miss it, or is it not implemented?
Thanks!

**Comment by fabian-dlr** [comment]
Hi,

> I didn't find its implementation in the OUTPOST - did I miss it, or is it not implemented?

No, you correct: As we are mainly using statically allocated memory, the RTEMS Memory Partition Manager has not been implemented yet.
