### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by leonpollak** [DLR-RY/outpost-core#3]
Hello. Please, be so kind to help to compile the library: any attempt to run "make" fails with the error:
EnvironmentError: No tool named 'utils_buildformat': not a Zip file:
I downloaded your SCons Tool Collection, but can't find the correct place to put it.
Please, advice.

**Comment by fabian-dlr** [comment]
You need to clone the `scons-build-tools` repository to the same folder the `outpost-core` repository resides in.

Something like the following should work (assuming you have the required tools installed):
```
$ git clone https://github.com/DLR-RY/scons-build-tools.git
$ git clone https://github.com/DLR-RY/outpost-core.git
$ cd outpost-core
$ make test
```
